name: Build Mod

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: Upload Mod
        uses: actions/upload-artifact@v4
        with:
          name: auto-keyboard
          path: build/libs/*.jar
